### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by ArduinoFan0** [aMelonRind/Stereopsis#1]
here are all my mods
![mods 2023-10-21 4_32_47 PM](https://github.com/aMelonRind/Stereopsis/assets/100047815/e61577a0-c482-4413-aade-a46a2378c007)

**Comment by Felix14-v2** [comment]
Probably Exordium incompatibility

**Comment by aMelonRind** [comment]
> Probably Exordium incompatibility

Probably yes, and I won't fix it.
Closing because no reply for too long.
